mysql:
  username: root
  password: docker
  schema: adm_videos
  url: localhost:3306
  dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  undertow:
      threads:
        worker: 10
        io: 2